### ISSUE TITLE
CreateTransfer Idempotent key 

### ISSUE THREAD

**Issue by wadearnold** [moovfinancial/moov-go#53]
The [Moov Post Transfer](https://docs.moov.io/api/money-movement/transfers/create/) endpoint requires an `X-Idempotency-Key` set in the header to prevent duplicate transfers from being created. Note that we only accept UUID v4.

The go SDK does not generate a UUID for the idempotency key nor does the [CreateTransfer() ](https://github.com/moovfinancial/moov-go/blob/201935b865c6e8bd97f79b21c11b51c0aad5e025/pkg/transfer.go#L185 )function take one as a parameter.  

Should the SDK manage the Idempotency key or should it allow one to be set to `WithIdepempotency()` ?

**Comment by adamdecaf** [comment]
IMO we should allow users to set a key. I can see us supplying one if left out as a safe default.

**Comment by InfernoJJ** [comment]
We're doing both and its all merged in. Random by default and they can override.
