### ISSUE TITLE
Consistent pattern for sync vs async function calls 

### ISSUE THREAD

**Issue by wadearnold** [moovfinancial/moov-go#60]
Multiple endpoints such as CreateAccount and CreateTransfer have an `x-wait-for` header that changes the response body. I am wondering if we need to pass a sync/async parameter to these function calls or just separate them into two different function calls such as moov.CreateTransfer() and moov.CreateTransferAsync() 

Not sure if most people will want the synchronous function call?

**Comment by alovak** [comment]
@wadearnold, I believe that for API calls such as creating an account, linking a card, most people will prefer the synchronous call. Asynchronous API calls place the responsibility of polling (or listening for webhooks) on the developer's shoulders, which doesn't make their life easier.

**Comment by InfernoJJ** [comment]
@alovak there is no polling or waiting the developers have to do.

**Comment by adamdecaf** [comment]
There are a few libraries which offer a Promise type we could use. 
- https://github.com/chebyrash/promise/blob/master/promise.go
- https://github.com/reugn/async/blob/master/promise.go
