### ISSUE TITLE
Verify the signature of a webhook

### ISSUE THREAD

**Issue by wadearnold** [moovfinancial/moov-go#82]
This project should be deprecated and added into the examples folder. 

https://github.com/moovfinancial/webhook-handler

**Comment by vxio** [comment]
Added in #98

**Comment by adamdecaf** [comment]
Can we close this issue now?

**Comment by wadearnold** [comment]
Looks solved to me. @vxio ?

**Comment by vxio** [comment]
All of this is in a feature branch, https://github.com/moovfinancial/moov-go/tree/feat-webhooks; I'll close this issue once we merge that feature branch to `main`

**Comment by vxio** [comment]
Handled in https://github.com/moovfinancial/moov-go/pull/112
